#+title: Lab Translation: Proof of Concept

* Objective

  It was agreed that the existing content may be made available in
  multilingual options or statespecific languages. IIIT Hyderabad has
  kindly agreed to recast one lab as a pilot in two language viz Hindi
  and Telegu in addition to English as default language.

* Motivation

  The *Virtual Labs* portal provides remote-access to Labs for
  engineering students to perform experiments and learn various
  concepts.  However, currently these labs are available only in English
  language, whereas a majority of Indian engineering students are more
  fluent in thier native languages as compared to English.  This makes
  it more difficult for the students to focus on learning the concepts
  as they spend more time understanding the language itself.
  
  The =Virtual Labs Translation= initiative aims to address this gap and
  improve the accessibility of Virtual Labs content by translating the
  labs from English to various Indian languges.  This phase of the
  translation project includes translation to =Hindi= and =Telugu=
  languges.

  

* Text Translation
  
  Translation of a lab (text content) to any given language involves
  the following steps:
  1. Pre-processing: Extraction of text from HTML
  2. Translation
  3. Post-processing: Build HTML files with translated text
     
** Pre-processing: Extraction of text from HTML

   The lab content is in HTML format.  It contains text, simulation
   and images.  This step deals only with the textual content.  For
   each HTML document, we extract the text content and place it in a
   text file with the same name (appended with a suffix) as the html
   document.

   These text documents are sent to the translation service.  The
   translation services are provided by =Language Translation Research
   Center (LTRC)= at IIIT Hyderabad.

** Translation

   The translation process requires the content (to be translated) in
   a text file.  Each line in the text file is translated separately,
   and the translated text (in the specified target language), is
   placed next to the source text in the same line, separated by a
   =TAB= charachter.

   Translation is two step process:
   1. Machine Translation
   2. Human Validation
      
*** Machine Translation
    
    In this step, a pre-trained =neural machine translation= system is
    used to translate each line of text in the source language, to a
    correspoding phrase (with the same/similar meaning) in the target
    language.

    This process takes a few seconds for each lab, per target
    language.  Next, the translated documents need to be validated by
    language experts (humans).

*** Human Validation (Text)

    A languge expert reads all the translated documents and fixes any
    errors and inconsistencies in the translated text.  After this
    process, the text should be indistinguishable from a something
    written by a human.

    The text content is now ready to be placed in the HTML documents.

** Post-processing: Build HTML files with translated text

*** Build HTML
    
    After the translation process, a translation map document
    corresponding to each html document is received from the
    translation service (LTRC).  Using these translation maps, each
    HTML document is translated to the target language.
    
    This is an automated process which takes a few seconds for each
    experiment, per target language.  This is followed by a validation
    step.

*** Human Validation (HTML)

    This validation is required to check for any errors that might have
    occured in the previous step that altered the structure of the html
    document, or if some text has not been translated.

* Image Transltion

  =WORK IN PROGRESS=

  The images need to be translated manually using some Photoshop tools.


* Simulation Translation
  
  =WORK IN PROGRESS=
  
  Experiment simulations are a combination of HTML and javascript.
  Most of the text is in HTML, but there are some messages, dynamic
  HTML, alerts etc, that are encoded in javasctipt sources.  These
  text strings also need to be translated, which is performed by
  extracting the strings from the javascript source and replacing them
  with translated text, using some a parsing tool.
  

* Time Estimates

Time estimates for each of the steps imvolved (per lab per language).

|-------+------------------------------+----------------+------------------|
| S. No | Process Step                 | Time Taken     | Team Responsible |
|-------+------------------------------+----------------+------------------|
|     1 | Extraction of text from HTML | O(seconds)     | VLEAD            |
|-------+------------------------------+----------------+------------------|
|     2 | Machine Translation          | O(seconds)     | LTRC             |
|-------+------------------------------+----------------+------------------|
|     3 | Human Validation             | 1 week per lab | LTRC             |
|-------+------------------------------+----------------+------------------|
|     4 | Building HTML                | O(seconds)     | VLEAD            |
|-------+------------------------------+----------------+------------------|
|     5 | Human Validation (HTML)      | 1 week per lab | VLEAD            |
|-------+------------------------------+----------------+------------------|
|     5 | Image Transltion             |                | VLEAD            |
|-------+------------------------------+----------------+------------------|
|     6 | Simulation Translation       | O(seconds)     | VLEAD            |
|-------+------------------------------+----------------+------------------|

* Case Study

  Following the above steps, translation of one lab =[NAME-OF-LAB]=
  from =English= to =Hindi= and =Telugu= was performed as a proof of
  concept.

  Approximate time taken for each step in the process in listed below:

|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
| S. No | Experiment Name                                                                                            | Manually Validated (text) | Manually Validated (HTML) | Time   | Simulation Status     | Images Translated |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    1. | Nuclear Magnetic Resosnace Spectrocopy and Evaulation of Simple 1H NMR Spectra of Select Organic Compounds | Yes                       | Yes                       | 2 days | JS, translated        | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    2. | Instrumentation and Working Principles of Infra Red (IR) Spectroscopy Using Salt Plates                    | Yes                       | Yes                       | 2 days | Flash, not translated | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    3. | Instrumentation and Working Principles of Solutions Infra Red (IR) Spectroscopy                            | Yes                       | Yes                       | 2 days | Flash, not translated | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    4. | Instrumentation and Working Principles of Mass Spectroscopy                                                | No                        | Yes                       | 1 day  | JS, translated        | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    5. | Determination of Molar Mass of Simple Compounds Using Mass Spectroscopy                                    | No                        | Yes                       | 1 day  | Flash, not translated | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|
|    6. | Identification of Unknown Components Using Spectroscopic Techniques                                        | No                        | Yes                       | 1 day  | Flash, not translated | No                |
|-------+------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+--------+-----------------------+-------------------|


* Caveats

There are some caveats in the translation process, which we are
currently working to address.

Caveats concerning the translation process:

1. Text in JS is currently not supported, needs to be done manually.
2. Translation of HTML is not completely accurate.  There are always
   some errors, which need to either fixed in the translation file, or
   the resulting HTML file.
