#+title: Minutes of Meeting

* <2019-11-01 Fri>

** Attendees

+ VLEAD: Priya Raman, Ojas Mohril
+ LTRC: Vandan Mujadia, Pruthwik Mishra

** Agenda

1. Understand the translation process (machine and human) followed by
   LTRC
2. Compare the Google translate and LTRC translation results
3. Time and effort estimation estimation
4. Assess the feasibility of access to LTRC translation API / software
   package

** Details

*** LTRC Translation process

The translation process followed by LTRC is human centered.  The text
extracted from HTML documents is fed into a workbench software
(developed by =eBhasha Setu Language Services=).  The purpose of this
workbench is to provide a convenient medium for the human validators
to perform their task.  The workbench has integration with Google
translation service as well as LTRC translation service.  Any one of
these can be chosen to perform machine translation of the plain text.
The LTRC machine translation supports three languages (Hindi/ Telugu
and ?) whereas Google translate supports hundreds of languages.  After
this step, the workbench provides with an interface to edit the
translated text. The human validators now perform the validation.
This process takes at least one to two days per experiment.

Alternatively the text can be translated externally and fed into the
workbench software for validation and editing.


*** Issues with machine translation

The automated machine translation service provided by Google translate
and LTRC are almost similar in most cases.  According to the LTRC
team, the machine translation process can not be trusted to always
provide semantically equivalent and meaningful translations in domain
specific scenarios.  They presented a few examples where the
translation process changes the meaning of the sentences.  Therefore,
according to LTRC, the human validation process is indispensable, and
people who are experts in linguistics and also understand the subject
matter are required for the validation process.


*** Time and effort estimation

|---------------------+-----------------------------------------+---------------------------------------------|
| Process             | Dependency                              | Time Estimate                               |
|---------------------+-----------------------------------------+---------------------------------------------|
| Machine translation | Google Translate / LTRC translation API | negligible                                  |
|---------------------+-----------------------------------------+---------------------------------------------|
| Human Validation    | Workbench and Validators                | LTRC estimate: 2 days per experiment        |
|                     |                                         | VLEAD estimate: 0.5 to 1 day per experiment |
|---------------------+-----------------------------------------+---------------------------------------------|

Following the recommendations from LTRC, language and domain experts
have to be hired for the validation process.  The validators will
study the translated content (probably using the workbench software)
and perform the necessary editing.  This step is estimated to take two
days per experiment.


*** Access to LTRC translation API

It is possible to gain access to the LTRC translation API over IIIT
network.  Followup (with Vandan) is required to gain the necessary
access.

** Tasks

1. Research about the =eBhasha Setu= workbench and other similar
   software.  Find out the exact functionality, pricing etc. and check
   if some open source alternative available.
2. Setup and test the LTRC translation service.
3. Need to setup a protocol for HTML to text and reverse mapping.
